version: '3'
services:
  spring-boot-mysql:
    build: .
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
     
    
  mysqldb:
    image: mysql
    platform: linux/x86_64
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: bootdb
  
