#!/bin/bash
# use to install httpd for user data
yumm update -y
yum install -y httpd
systemctl start httpd
systemctl enable httpd
echo "<h1>Hello from $(hostname -f) !! It is EC2 Instance user data</h1>" > /var/www/html/index.html