apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-python
  template:
    metadata:
      labels:
        app: first-python
    spec:
      containers:
      - name: first-python
        image: shalini06mittal/first-python
        ports:
        - containerPort: 4000
