version: '3'
services:
  spring-boot-mysql:
    build: ./SpringWebDemo/
    platform: linux/x86_64
    ports:
      - 8082:8081
    networks:
      - spring-mysql
    depends_on:
      - mysqldb
    
    
  mysqldb:
    image: mysql
    platform: linux/x86_64
    ports:
      - 8889:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bootdb
      MYSQL_USER: sa
      MYSQL_PASSWORD: root
    networks:
      - spring-mysql
  adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
networks:
  spring-mysql:
